/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMyJobsRouteImport } from './routes/_authenticated/my-jobs'
import { Route as AuthenticatedMyProjectTasksRouteImport } from './routes/_authenticated/my-project-tasks'
import { Route as AuthenticatedMyProjectsRouteImport } from './routes/_authenticated/my-projects'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSharedFilesRouteImport } from './routes/_authenticated/shared-files'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedWorkOrdersRouteImport } from './routes/_authenticated/work-orders'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthenticatedJobReportJobIdRouteImport } from './routes/_authenticated/job-report/$jobId'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs/$jobId'
import { Route as AuthenticatedProjectReportProjectIdRouteImport } from './routes/_authenticated/project-report/$projectId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyJobsRoute = AuthenticatedMyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyProjectTasksRoute =
  AuthenticatedMyProjectTasksRouteImport.update({
    id: '/my-project-tasks',
    path: '/my-project-tasks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyProjectsRoute = AuthenticatedMyProjectsRouteImport.update({
  id: '/my-projects',
  path: '/my-projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSharedFilesRoute =
  AuthenticatedSharedFilesRouteImport.update({
    id: '/shared-files',
    path: '/shared-files',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkOrdersRoute = AuthenticatedWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJobReportJobIdRoute =
  AuthenticatedJobReportJobIdRouteImport.update({
    id: '/job-report/$jobId',
    path: '/job-report/$jobId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectReportProjectIdRoute =
  AuthenticatedProjectReportProjectIdRouteImport.update({
    id: '/project-report/$projectId',
    path: '/project-report/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-jobs': typeof AuthenticatedMyJobsRoute
  '/my-project-tasks': typeof AuthenticatedMyProjectTasksRoute
  '/my-projects': typeof AuthenticatedMyProjectsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/shared-files': typeof AuthenticatedSharedFilesRoute
  '/stock': typeof AuthenticatedStockRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/job-report/$jobId': typeof AuthenticatedJobReportJobIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/project-report/$projectId': typeof AuthenticatedProjectReportProjectIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-jobs': typeof AuthenticatedMyJobsRoute
  '/my-project-tasks': typeof AuthenticatedMyProjectTasksRoute
  '/my-projects': typeof AuthenticatedMyProjectsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/shared-files': typeof AuthenticatedSharedFilesRoute
  '/stock': typeof AuthenticatedStockRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/job-report/$jobId': typeof AuthenticatedJobReportJobIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/project-report/$projectId': typeof AuthenticatedProjectReportProjectIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-jobs': typeof AuthenticatedMyJobsRoute
  '/_authenticated/my-project-tasks': typeof AuthenticatedMyProjectTasksRoute
  '/_authenticated/my-projects': typeof AuthenticatedMyProjectsRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/shared-files': typeof AuthenticatedSharedFilesRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_authenticated/job-report/$jobId': typeof AuthenticatedJobReportJobIdRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/project-report/$projectId': typeof AuthenticatedProjectReportProjectIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/approvals'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/my-jobs'
    | '/my-project-tasks'
    | '/my-projects'
    | '/offers'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/shared-files'
    | '/stock'
    | '/tasks'
    | '/team'
    | '/work-orders'
    | '/oauth/consent'
    | '/job-report/$jobId'
    | '/jobs/$jobId'
    | '/project-report/$projectId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/approvals'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/my-jobs'
    | '/my-project-tasks'
    | '/my-projects'
    | '/offers'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/shared-files'
    | '/stock'
    | '/tasks'
    | '/team'
    | '/work-orders'
    | '/oauth/consent'
    | '/job-report/$jobId'
    | '/jobs/$jobId'
    | '/project-report/$projectId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/approvals'
    | '/_authenticated/calendar'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-jobs'
    | '/_authenticated/my-project-tasks'
    | '/_authenticated/my-projects'
    | '/_authenticated/offers'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/shared-files'
    | '/_authenticated/stock'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/_authenticated/work-orders'
    | '/oauth/consent'
    | '/_authenticated/job-report/$jobId'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/project-report/$projectId'
    | '/_authenticated/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-jobs': {
      id: '/_authenticated/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof AuthenticatedMyJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-project-tasks': {
      id: '/_authenticated/my-project-tasks'
      path: '/my-project-tasks'
      fullPath: '/my-project-tasks'
      preLoaderRoute: typeof AuthenticatedMyProjectTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-projects': {
      id: '/_authenticated/my-projects'
      path: '/my-projects'
      fullPath: '/my-projects'
      preLoaderRoute: typeof AuthenticatedMyProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shared-files': {
      id: '/_authenticated/shared-files'
      path: '/shared-files'
      fullPath: '/shared-files'
      preLoaderRoute: typeof AuthenticatedSharedFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/work-orders': {
      id: '/_authenticated/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof AuthenticatedWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/job-report/$jobId': {
      id: '/_authenticated/job-report/$jobId'
      path: '/job-report/$jobId'
      fullPath: '/job-report/$jobId'
      preLoaderRoute: typeof AuthenticatedJobReportJobIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project-report/$projectId': {
      id: '/_authenticated/project-report/$projectId'
      path: '/project-report/$projectId'
      fullPath: '/project-report/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectReportProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyJobsRoute: typeof AuthenticatedMyJobsRoute
  AuthenticatedMyProjectTasksRoute: typeof AuthenticatedMyProjectTasksRoute
  AuthenticatedMyProjectsRoute: typeof AuthenticatedMyProjectsRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSharedFilesRoute: typeof AuthenticatedSharedFilesRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWorkOrdersRoute: typeof AuthenticatedWorkOrdersRoute
  AuthenticatedJobReportJobIdRoute: typeof AuthenticatedJobReportJobIdRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedProjectReportProjectIdRoute: typeof AuthenticatedProjectReportProjectIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyJobsRoute: AuthenticatedMyJobsRoute,
  AuthenticatedMyProjectTasksRoute: AuthenticatedMyProjectTasksRoute,
  AuthenticatedMyProjectsRoute: AuthenticatedMyProjectsRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSharedFilesRoute: AuthenticatedSharedFilesRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWorkOrdersRoute: AuthenticatedWorkOrdersRoute,
  AuthenticatedJobReportJobIdRoute: AuthenticatedJobReportJobIdRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedProjectReportProjectIdRoute:
    AuthenticatedProjectReportProjectIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
