-- NES Enerji İş Takip - güvenlik ve operasyon akışları
-- Bu migration, önceki temel şemadan sonra çalıştırılır.

-- Fotoğraf kategorileri
DO $$
BEGIN
  CREATE TYPE public.photo_type AS ENUM ('saha', 'montaj_sonrasi', 'malzeme', 'diger');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS company_name TEXT;

ALTER TABLE public.work_orders
  ADD COLUMN IF NOT EXISTS work_order_no BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS work_orders_work_order_no_key
  ON public.work_orders (work_order_no);

ALTER TABLE public.photos
  ADD COLUMN IF NOT EXISTS photo_type public.photo_type NOT NULL DEFAULT 'saha';

ALTER TABLE public.stock_items
  ADD COLUMN IF NOT EXISTS code TEXT,
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS min_quantity NUMERIC(14,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS description TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS stock_items_code_key
  ON public.stock_items (code);

-- Finansal alanlar müşteri/taşeron satırından fiziksel olarak ayrılır.
-- RLS satırı gizler; sütunu gizlemez. Bu tablo yalnızca yöneticilere açıktır.
CREATE TABLE IF NOT EXISTS public.work_order_financials (
  work_order_id UUID PRIMARY KEY REFERENCES public.work_orders(id) ON DELETE CASCADE,
  total_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  approved_progress_pct INT NOT NULL DEFAULT 0 CHECK (approved_progress_pct BETWEEN 0 AND 100),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.work_order_financials (
  work_order_id, total_amount, approved_progress_pct
)
SELECT id, total_amount, approved_progress_pct
FROM public.work_orders
ON CONFLICT (work_order_id) DO NOTHING;

ALTER TABLE public.work_orders
  DROP COLUMN approved_progress_pct,
  DROP COLUMN total_amount;

ALTER TABLE public.work_order_financials ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.work_order_financials TO authenticated;
GRANT ALL ON public.work_order_financials TO service_role;
DROP POLICY IF EXISTS "wof_admin_all" ON public.work_order_financials;
CREATE POLICY "wof_admin_all" ON public.work_order_financials
  FOR ALL TO authenticated
  USING (public.has_role((SELECT auth.uid()), 'admin'))
  WITH CHECK (public.has_role((SELECT auth.uid()), 'admin'));

-- SECURITY DEFINER fonksiyonlarında güvenli search_path kullanılır.
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role public.app_role)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (
    NEW.id,
    COALESCE(
      NULLIF(NEW.raw_user_meta_data->>'full_name', ''),
      NULLIF(split_part(COALESCE(NEW.email, ''), '@', 1), ''),
      'Kullanıcı'
    )
  );
  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'customer');
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.apply_stock_movement()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM 1
  FROM public.stock_items
  WHERE id = NEW.stock_item_id AND quantity >= NEW.quantity
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Yetersiz stok veya geçersiz stok kartı';
  END IF;

  UPDATE public.stock_items
  SET quantity = quantity - NEW.quantity
  WHERE id = NEW.stock_item_id;
  RETURN NEW;
END;
$$;

ALTER TABLE public.stock_movements
  DROP CONSTRAINT IF EXISTS stock_movements_quantity_positive;
ALTER TABLE public.stock_movements
  ADD CONSTRAINT stock_movements_quantity_positive CHECK (quantity > 0);

CREATE TABLE IF NOT EXISTS public.work_order_materials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  work_order_id UUID NOT NULL REFERENCES public.work_orders(id) ON DELETE CASCADE,
  stock_item_id UUID REFERENCES public.stock_items(id) ON DELETE SET NULL,
  custom_material_name TEXT,
  quantity NUMERIC(14,3) NOT NULL CHECK (quantity > 0),
  unit TEXT NOT NULL,
  is_nes_stock BOOLEAN NOT NULL DEFAULT false,
  added_by UUID NOT NULL REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT work_order_materials_source_check CHECK (
    (is_nes_stock = true AND stock_item_id IS NOT NULL)
    OR
    (is_nes_stock = false AND NULLIF(trim(custom_material_name), '') IS NOT NULL)
  )
);

ALTER TABLE public.work_order_materials ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.work_order_materials TO authenticated;
GRANT ALL ON public.work_order_materials TO service_role;

-- Profil bilgileri yalnızca kişinin kendisi ve yöneticiler tarafından görülür.
DROP POLICY IF EXISTS "profiles_authenticated_read" ON public.profiles;
DROP POLICY IF EXISTS "profiles_self_insert" ON public.profiles;
DROP POLICY IF EXISTS "profiles_admin_read" ON public.profiles;
DROP POLICY IF EXISTS "profiles_self_read" ON public.profiles;
CREATE POLICY "profiles_admin_read" ON public.profiles
  FOR SELECT TO authenticated
  USING (public.has_role((SELECT auth.uid()), 'admin'));
CREATE POLICY "profiles_self_read" ON public.profiles
  FOR SELECT TO authenticated
  USING (id = (SELECT auth.uid()));

-- Yöneticiler kullanıcı rollerini yönetebilir.
GRANT INSERT, UPDATE, DELETE ON public.user_roles TO authenticated;
DROP POLICY IF EXISTS "roles_admin_all" ON public.user_roles;
CREATE POLICY "roles_admin_all" ON public.user_roles
  FOR ALL TO authenticated
  USING (public.has_role((SELECT auth.uid()), 'admin'))
  WITH CHECK (public.has_role((SELECT auth.uid()), 'admin'));

-- Taşeron iş emrinin finansal/yönetim alanlarını doğrudan değiştiremez.
DROP POLICY IF EXISTS "wo_contractor_update" ON public.work_orders;

-- Stok tüketimi yalnızca kontrollü RPC üzerinden yapılır.
DROP POLICY IF EXISTS "sm_contractor_insert" ON public.stock_movements;
REVOKE INSERT ON public.stock_movements FROM authenticated;

-- İş emri malzeme politikaları
DROP POLICY IF EXISTS "wom_admin_all" ON public.work_order_materials;
DROP POLICY IF EXISTS "wom_contractor_read" ON public.work_order_materials;
DROP POLICY IF EXISTS "wom_contractor_insert" ON public.work_order_materials;
CREATE POLICY "wom_admin_all" ON public.work_order_materials
  FOR ALL TO authenticated
  USING (public.has_role((SELECT auth.uid()), 'admin'))
  WITH CHECK (public.has_role((SELECT auth.uid()), 'admin'));
CREATE POLICY "wom_contractor_read" ON public.work_order_materials
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.work_order_assignments a
      WHERE a.work_order_id = work_order_materials.work_order_id
        AND a.contractor_id = (SELECT auth.uid())
    )
  );
CREATE POLICY "wom_contractor_insert" ON public.work_order_materials
  FOR INSERT TO authenticated
  WITH CHECK (
    added_by = (SELECT auth.uid())
    AND is_nes_stock = false
    AND EXISTS (
      SELECT 1
      FROM public.work_order_assignments a
      WHERE a.work_order_id = work_order_materials.work_order_id
        AND a.contractor_id = (SELECT auth.uid())
    )
  );

-- Güvenli rol değiştirme
CREATE OR REPLACE FUNCTION public.set_user_role(
  target_user_id UUID,
  new_role public.app_role
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NOT public.has_role((SELECT auth.uid()), 'admin') THEN
    RAISE EXCEPTION 'Bu işlem için yönetici yetkisi gerekir';
  END IF;

  DELETE FROM public.user_roles WHERE user_id = target_user_id;
  INSERT INTO public.user_roles (user_id, role) VALUES (target_user_id, new_role);
END;
$$;

-- İş emri ve taşeron ataması tek transaction içinde oluşturulur.
CREATE OR REPLACE FUNCTION public.create_work_order(
  target_customer_id UUID,
  order_title TEXT,
  order_description TEXT,
  order_location TEXT,
  order_scheduled_at TIMESTAMPTZ,
  order_total_amount NUMERIC,
  visible_to_customer BOOLEAN,
  assigned_contractor_id UUID DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_user_id UUID := (SELECT auth.uid());
  new_work_order_id UUID;
BEGIN
  IF NOT public.has_role(current_user_id, 'admin') THEN
    RAISE EXCEPTION 'Bu işlem için yönetici yetkisi gerekir';
  END IF;
  IF NULLIF(trim(order_title), '') IS NULL THEN
    RAISE EXCEPTION 'İş emri başlığı zorunludur';
  END IF;
  IF order_total_amount < 0 THEN
    RAISE EXCEPTION 'İş bedeli negatif olamaz';
  END IF;

  INSERT INTO public.work_orders (
    customer_id,
    title,
    description,
    location,
    scheduled_at,
    show_to_customer,
    created_by
  ) VALUES (
    target_customer_id,
    trim(order_title),
    NULLIF(trim(order_description), ''),
    NULLIF(trim(order_location), ''),
    order_scheduled_at,
    visible_to_customer,
    current_user_id
  )
  RETURNING id INTO new_work_order_id;

  INSERT INTO public.work_order_financials (work_order_id, total_amount)
  VALUES (new_work_order_id, order_total_amount);

  IF assigned_contractor_id IS NOT NULL THEN
    IF NOT public.has_role(assigned_contractor_id, 'contractor') THEN
      RAISE EXCEPTION 'Seçilen kullanıcı taşeron rolünde değil';
    END IF;
    INSERT INTO public.work_order_assignments (work_order_id, contractor_id)
    VALUES (new_work_order_id, assigned_contractor_id);
  END IF;

  RETURN new_work_order_id;
END;
$$;

-- Taşeron ilerleme bildirimi: yalnızca ilerleme alanını değiştirir.
CREATE OR REPLACE FUNCTION public.submit_progress_update(
  target_work_order_id UUID,
  new_pct INT,
  progress_note TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_user_id UUID := (SELECT auth.uid());
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'Oturum bulunamadı';
  END IF;
  IF new_pct < 0 OR new_pct > 100 THEN
    RAISE EXCEPTION 'İlerleme 0 ile 100 arasında olmalıdır';
  END IF;
  IF NOT public.has_role(current_user_id, 'admin')
     AND NOT EXISTS (
       SELECT 1 FROM public.work_order_assignments a
       WHERE a.work_order_id = target_work_order_id
         AND a.contractor_id = current_user_id
     ) THEN
    RAISE EXCEPTION 'Bu iş emri size atanmamış';
  END IF;

  INSERT INTO public.progress_updates (work_order_id, contractor_id, pct, note)
  VALUES (target_work_order_id, current_user_id, new_pct, NULLIF(trim(progress_note), ''));

  UPDATE public.work_orders
  SET progress_pct = new_pct,
      status = CASE
        WHEN new_pct = 100 THEN 'completed'::public.work_status
        WHEN new_pct > 0 THEN 'in_progress'::public.work_status
        ELSE status
      END,
      updated_at = now()
  WHERE id = target_work_order_id;
END;
$$;

-- Stok tüketimi: satırı kilitler, yeterli stok yoksa hiçbir kayıt oluşturmaz.
CREATE OR REPLACE FUNCTION public.consume_stock_item(
  target_stock_item_id UUID,
  target_work_order_id UUID,
  consumed_quantity NUMERIC,
  movement_note TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_user_id UUID := (SELECT auth.uid());
  available_quantity NUMERIC;
  item_unit public.stock_unit;
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'Oturum bulunamadı';
  END IF;
  IF consumed_quantity <= 0 THEN
    RAISE EXCEPTION 'Miktar sıfırdan büyük olmalıdır';
  END IF;
  IF NOT public.has_role(current_user_id, 'admin')
     AND NOT EXISTS (
       SELECT 1 FROM public.work_order_assignments a
       WHERE a.work_order_id = target_work_order_id
         AND a.contractor_id = current_user_id
     ) THEN
    RAISE EXCEPTION 'Bu iş emri size atanmamış';
  END IF;

  SELECT quantity, unit
  INTO available_quantity, item_unit
  FROM public.stock_items
  WHERE id = target_stock_item_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Malzeme bulunamadı';
  END IF;
  IF item_unit = 'adet' AND consumed_quantity <> trunc(consumed_quantity) THEN
    RAISE EXCEPTION 'Adet biriminde küsurat kullanılamaz';
  END IF;
  IF available_quantity < consumed_quantity THEN
    RAISE EXCEPTION 'Yetersiz stok. Mevcut: %', available_quantity;
  END IF;

  INSERT INTO public.stock_movements (
    stock_item_id, work_order_id, contractor_id, quantity, note
  ) VALUES (
    target_stock_item_id,
    target_work_order_id,
    current_user_id,
    consumed_quantity,
    NULLIF(trim(movement_note), '')
  );

  INSERT INTO public.work_order_materials (
    work_order_id, stock_item_id, quantity, unit, is_nes_stock, added_by
  ) VALUES (
    target_work_order_id,
    target_stock_item_id,
    consumed_quantity,
    item_unit::TEXT,
    true,
    current_user_id
  );
END;
$$;

-- Hakediş onayı sunucu tarafında hesaplanır.
CREATE OR REPLACE FUNCTION public.approve_progress(
  target_work_order_id UUID,
  approved_pct_value INT
)
RETURNS NUMERIC
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_user_id UUID := (SELECT auth.uid());
  order_total NUMERIC;
  approval_amount NUMERIC;
BEGIN
  IF NOT public.has_role(current_user_id, 'admin') THEN
    RAISE EXCEPTION 'Bu işlem için yönetici yetkisi gerekir';
  END IF;
  IF approved_pct_value < 0 OR approved_pct_value > 100 THEN
    RAISE EXCEPTION 'Onay yüzdesi 0 ile 100 arasında olmalıdır';
  END IF;

  SELECT total_amount INTO order_total
  FROM public.work_order_financials
  WHERE work_order_id = target_work_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'İş emri bulunamadı';
  END IF;

  approval_amount := round(order_total * approved_pct_value / 100, 2);

  UPDATE public.work_order_financials
  SET approved_progress_pct = approved_pct_value, updated_at = now()
  WHERE work_order_id = target_work_order_id;

  INSERT INTO public.progress_approvals (
    work_order_id, approved_pct, approved_amount, approved_by
  ) VALUES (
    target_work_order_id, approved_pct_value, approval_amount, current_user_id
  );

  RETURN approval_amount;
END;
$$;

REVOKE ALL ON FUNCTION public.set_user_role(UUID, public.app_role) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.create_work_order(UUID, TEXT, TEXT, TEXT, TIMESTAMPTZ, NUMERIC, BOOLEAN, UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.submit_progress_update(UUID, INT, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.consume_stock_item(UUID, UUID, NUMERIC, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.approve_progress(UUID, INT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_user_role(UUID, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_work_order(UUID, TEXT, TEXT, TEXT, TIMESTAMPTZ, NUMERIC, BOOLEAN, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_progress_update(UUID, INT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.consume_stock_item(UUID, UUID, NUMERIC, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_progress(UUID, INT) TO authenticated;

-- Özel fotoğraf bucket'ı
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'work-photos',
  'work-photos',
  false,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO UPDATE
SET public = false,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Önceki dar storage politikalarını güvenli iş emri erişimiyle değiştir.
DROP POLICY IF EXISTS "wp_contractor_read_own" ON storage.objects;
DROP POLICY IF EXISTS "wp_contractor_read_assigned" ON storage.objects;
DROP POLICY IF EXISTS "wp_contractor_delete_own" ON storage.objects;
CREATE POLICY "wp_contractor_read_assigned" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'work-photos'
    AND public.has_role((SELECT auth.uid()), 'contractor')
    AND EXISTS (
      SELECT 1
      FROM public.photos p
      JOIN public.work_order_assignments a ON a.work_order_id = p.work_order_id
      WHERE p.storage_path = storage.objects.name
        AND a.contractor_id = (SELECT auth.uid())
    )
  );
CREATE POLICY "wp_contractor_delete_own" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'work-photos'
    AND public.has_role((SELECT auth.uid()), 'contractor')
    AND (storage.foldername(name))[1] = (SELECT auth.uid())::TEXT
  );
